### PR TITLE
fixed routing without token

### PR DESCRIPTION
**Pull request by QuadDepo**

### CODE REVIEW

**Comment by Banjerr** [comment]
looks good to me. thanks for the help!

**Comment by QuadDepo** [comment]
Does this count as Hacktober?

**Comment by QuadDepo** [comment]
No problem btw,

Do you know the background color is different shades? i really couldnt figure it out. Driving me crazy haha

**Comment by Banjerr** [comment]
I believe it does count; I think technically any Pull Request counts; even if it doesn't get merged in.

I did not know that about the background. lol. I haven't worked on this project in almost a year; was mainly just to play around with Electron and Angular.

**Comment by QuadDepo** [comment]
Ah oke haha :-)

**Pull request merged**
